### ISSUE TITLE
You should switch to pure patches so you are not distributing copyrighted code

### ISSUE THREAD

**Issue by jimmckeeth** [chinawsb/fmxfixes#2]
You have a notice letting people know they should have the source, but you are in violation of the copyright by distributing it still. Instead, you can use pure patches that only contain the differences. Then you will no longer be violating the copyright.

Here is some documentation on DiffUtil and Patch that you can use to create pure patches.
http://gnuwin32.sourceforge.net/packages/diffutils.htm
http://gnuwin32.sourceforge.net/packages/patch.htm

**Comment by PonyPC** [comment]
Sorry, we got it that we should not distribute the source code. We'll change it to patch files immediately. Thanks for pointing out. Anyway, we wish Delphi become more stable and easy to use, and fixing existing bugs as soon as possible.

**Comment by chinawsb** [comment]
OK,changed
